# Lab 1 specific
    ! operators
    sum=Sum
    diff=Difference
    product=Product
    quot=Quotient

    ! results
    op1=Operand 1
    oper=Operator
    op2=Operand 2

# Lab 2 specific
    ! class names
    book=Book
    picture=Picture
    shoe=Shoe
    toy=Toy

    ! others
    prod_impl_present=Products that implements Present interface:
    yes=Yes
    prod=Product #
    is_a=is a

# Lab 3 specific
    ! threads
    producer=Producer
    consumer=Consumer

    ! storage messages
    prod_good=produced number
    prod_bad=produced bad number
    cons=consumed number

# Shared
arg_set=Given next arguments set:

# Errors
    ! Lab 1 specific
    error_args=wrong arguments. Use following format: [operand] [operator] [operand]
    error_operands=wrong arguments. Operands must be integer or float numbers
    error_operator=wrong operator. Should be '+', '-', 'x' or '/'

    ! Lab 2 specific
    error_argument=wrong argument. Should be an integer
    error_random=some internal error in random function work